// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
// Example:
// ```dart
// import 'firebase_options.dart';
// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALq2VqNoUJMHMwS96J5bdeA-n36Vh1y-k',
    appId: '1:154502624282:web:cbb15cdda0dffed8380da3',
    messagingSenderId: '154502624282',
    projectId: 'seventeencentury-8fb55',
    authDomain: 'seventeencentury-8fb55.firebaseapp.com',
    storageBucket: 'seventeencentury-8fb55.appspot.com',
    measurementId: 'G-V6XZ055TN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Wnmi4S8jBnd6lKW-0i8wUFHtIODAzv4',
    appId: '1:154502624282:android:672ca4254e40598a380da3',
    messagingSenderId: '154502624282',
    projectId: 'seventeencentury-8fb55',
    storageBucket: 'seventeencentury-8fb55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqI35IxKbTg9mx-Ft2ffmf1bwk0kDi6tQ',
    appId: '1:154502624282:ios:1b22bc6934d02c07380da3',
    messagingSenderId: '154502624282',
    projectId: 'seventeencentury-8fb55',
    storageBucket: 'seventeencentury-8fb55.appspot.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqI35IxKbTg9mx-Ft2ffmf1bwk0kDi6tQ',
    appId: '1:154502624282:ios:1b22bc6934d02c07380da3',
    messagingSenderId: '154502624282',
    projectId: 'seventeencentury-8fb55',
    storageBucket: 'seventeencentury-8fb55.appspot.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALq2VqNoUJMHMwS96J5bdeA-n36Vh1y-k',
    appId: '1:154502624282:web:e44cd6e725306e18380da3',
    messagingSenderId: '154502624282',
    projectId: 'seventeencentury-8fb55',
    authDomain: 'seventeencentury-8fb55.firebaseapp.com',
    storageBucket: 'seventeencentury-8fb55.appspot.com',
    measurementId: 'G-VQPMRPXHSX',
  );
}
